### ISSUE TITLE
Add use of Centos image to CI workflow

### ISSUE THREAD

**Issue by Castaglia** [proftpd/proftpd#1260]
The scope of this task is to add building/running of ProFTPD and its tests on a Centos image in the CI workflow, in addition to the existing Ubuntu image.

As @pghmcfc noted in [this PR](https://github.com/proftpd/proftpd/pull/1259), there are some compiler warnings/errors that might be picked up on that popular platform that may not necessarily be seen on Ubuntu.

**Comment by Castaglia** [comment]
Note that this may be more involved than expected; Centos is _not_ one of the supported GitHub Action [runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).  Thus for this, we may need a separate (but similar) workflow that runs a Centos Docker image on an Ubuntu runner.

Or perhaps not; I think we might just need to specify the [container](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) explicitly.  Which we should do anyway; I currently expect the build actions to be run in a Docker container, not on the runner host, anyway.

**Comment by Castaglia** [comment]
Something like:
```
jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:18.04', 'centos:8']
```
And then the provisioning steps (installing necessary packages), compiler tests, _etc_ will need adjustment.
