### ISSUE TITLE
ProFTPD with SSL/TLS filetransfer getting failed

### ISSUE THREAD

**Issue by subbiahvicky** [proftpd/proftpd#1825]
I have setup my Proftpd server on AWS EKS pod,

where my Dockerfile as:
```
# Use Ubuntu as the base image
FROM ubuntu:20.04

# Install required packages, including ProFTPD with mod_ident
RUN apt-get update && apt-get install -y \
    proftpd-basic \
    proftpd-mod-vroot \
    nano \
    openssl \
    && rm -rf /var/lib/apt/lists/*

# Create user 'Intel' with password 'issl@2023'
RUN useradd -m Intel && echo "Intel:issl@2023" | chpasswd

# Create the directory for Intel's FTP access
RUN mkdir -p /var/Intel/files && \
    chown Intel:Intel /var/Intel/files && \
    chmod 755 /var/Intel/files

# Copy the ProFTPD configuration file to the container
COPY proftpd.conf /etc/proftpd/proftpd.conf
COPY proftpd-ssl.conf /etc/proftpd/proftpd-ssl.conf
COPY proftpd.crt  /etc/ssl/certs/proftpd.crt
COPY proftpd.key  /etc/ssl/private/proftpd.key

# Ensure only Intel user can access the directory
RUN chown Intel:Intel /var/Intel/files
RUN chmod 600 /etc/ssl/private/proftpd.key && \
    chmod 644 /etc/ssl/certs/proftpd.crt

# Expose FTP ports (21 for control, 49152-49156 for passive data)
EXPOSE 21 49152-49156

# Command to start ProFTPD in non-daemon mode
CMD ["proftpd", "--nodaemon"]
```
proftpd.conf file as:
```
ServerName                      "proftpdtest.intel.com"
ServerType                      standalone
DefaultServer                   on

# Port 21 is the standard FTP port
Port                            21

# Load the SSL module
LoadModule mod_tls.c

# Passive mode ports
#PassivePorts                    49152 49162
<Global>
  PassivePorts 49152 49162
  MasqueradeAddress proftpdtest.intel.com
</Global>

# Set up user and group for the FTP service
User                            Intel
Group                           Intel

# Default root directory for Intel user
DefaultRoot                     /var/Intel/files Intel

# Configure timeout settings
TimeoutNoTransfer               3600
TimeoutStalled                  3600
TimeoutIdle                     3600

MaxInstances                     30
MaxClients                       20

# Create a directory for storing user files
<Directory /var/Intel/files>
  Umask                         022 022  # Sets file/directory permissions
  AllowOverwrite                on
  <Limit ALL>
    AllowUser Intel
    DenyAll
  </Limit>
</Directory>

# Logging
SystemLog                       /var/log/proftpd/proftpd.log
TransferLog                     /var/log/proftpd/xferlog
ExtendedLog                     /var/log/proftpd/ftpstats.log
ExtendedLog                     /var/log/proftpd/bandwidth.log ALL bandwidth

# Log Format: Bandwidth Logging
LogFormat bandwidth "%b %m %U@%H %f"

# Allow passive mode data transfer
UseIPv6                         off
#IdentLookups                    off

# Enable TLS
#<IfModule mod_tls.c>
#    TLSEngine                   on
#    TLSLog                      /var/log/proftpd/tls.log
#    TLSProtocol                 TLSv1.2 TLSv1.3
#    TLSRSACertificateFile       /etc/ssl/certs/proftpd.crt
#    TLSRSACertificateKeyFile    /etc/ssl/private/proftpd.key
#    TLSOptions                  NoCertRequest NoSessionReuseRequired EnableDiags
#    TLSVerifyClient             off
#    TLSRequired                 on
    # Stronger cipher suite settings
#    TLSCipherSuite              HIGH:!aNULL:!MD5:!3DES:!DES:!SSLv2:!RC4
#    TLSImplicit                 off
    # Disable renegotiation to avoid SSL_accept errors
#    TLSRenegotiate              none
#</IfModule>

# Disable the delay engine to avoid warnings
<IfModule mod_delay.c>
    DelayEngine off
</IfModule>

# Allow the Intel user to write to their directory
#<Directory /var/Intel/files>
#  <Limit WRITE>
#    AllowAll
#  </Limit>
#</Directory>

# Include additional configurations from the conf.d directory
Include                         /etc/proftpd/conf.d/*.conf

# Include the SSL/TLS configuration
Include /etc/proftpd/

proftpd-ssl.conf as:

# Enable TLS
TLSEngine on

# Set the path for the SSL certificate and key
TLSRSACertificateFile    /etc/ssl/certs/proftpd.crt
TLSRSACertificateKeyFile /etc/ssl/private/proftpd.key

# Require TLS for all connections
TLSRequired on

# Enable implicit TLS on port 990
#TLSImplicit off
#TLSRenegotiate required
TLSRenegotiate none

# Allow explicit TLS/SSL connections
TLSProtocol TLSv1.2

# TLS options
TLSCipherSuite HIGH:!aNULL:!MD5
TLSOptions NoSessionReuseRequired

# SSL/TLS log file
TLSLog /var/log/proftpd/tls.log
```
purchased SSL/TLS certificate from Lets Encrypt and mapped the Network Loadbalancer as CName record in the domain controller.

where kubernetes yaml file as:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proftpd-server
  labels:
    app: proftpd
spec:
  selector:
    matchLabels:
      app: proftpd
  replicas: 1
  template:
    metadata:
      labels:
        app: proftpd
        service: proftpd-service
    spec:
      containers:
      - name: proftpd-server
        image: 878426365536.dkr.ecr.us-east-2.amazonaws.com/intel_cloud:proftpd
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "700m"
          limits:
            memory: "1200Mi"
            cpu: "1500m"
        ports:
        - containerPort: 22
          name: sftp
        - containerPort: 21
          name: ftps
        - containerPort: 20
          name: ftps-data
        - containerPort: 49152
          name: passive-ports
        - containerPort: 49153
          name: passive-ports1
        - containerPort: 49154
          name: passive-ports2
        - containerPort: 49155
          name: passive-ports3
        - containerPort: 49156
          name: passive-ports4
        - containerPort: 49157
          name: passive-ports5
        - containerPort: 49158
          name: passive-ports6
        - containerPort: 49159
          name: passive-ports7
        - containerPort: 49160
          name: passive-ports8
        - containerPort: 49161
          name: passive-ports9
        - containerPort: 49162
          name: passive-ports10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # Maximum number of pods that can be created over the desired replicas
      maxUnavailable: 0  # Maximum number of pods that can be unavailable during the update
---
apiVersion: v1
kind: Service
metadata:
  name: proftpd-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: proftpd
spec:
  type: LoadBalancer
  selector:
    app: proftpd
  ports:
  - name: sftp
    port: 22
    targetPort: sftp
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-data
    port: 20
    protocol: TCP
    targetPort: 20
  - name: passive-ports
    port: 49152
    targetPort: 49152
    protocol: TCP
  - name: passive-ports1
    port: 49153
    targetPort: 49153
    protocol: TCP
  - name: passive-ports2
    port: 49154
    targetPort: 49154
    protocol: TCP
  - name: passive-ports3
    port: 49155
    targetPort: 49155
    protocol: TCP
  - name: passive-ports4
    port: 49156
    targetPort: 49156
    protocol: TCP
  - name: passive-ports5
    port: 49157
    targetPort: 49157
    protocol: TCP
  - name: passive-ports6
    port: 49158
    targetPort: 49158
    protocol: TCP
  - name: passive-ports7
    port: 49159
    targetPort: 49159
    protocol: TCP
  - name: passive-ports8
    port: 49160
    targetPort: 49160
    protocol: TCP
  - name: passive-ports9
    port: 49161
    targetPort: 49161
    protocol: TCP
  - name: passive-ports10
    port: 49162
    targetPort: 49162
    protocol: TCP
```
where when i run `proftpd -V`, the output as:
```
Compile-time Settings:
  Version: 1.3.6c (maint)
  Platform: LINUX [Linux 5.10.219-208.866.amzn2.x86_64 x86_64]
  Built: Thu Feb 27 2020 19:34:56 UTC
  Built With:
    configure  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--enable-ipv6' '--enable-nls' '--enable-memcache' '--with-lastlog=/var/log/lastlog' '--enable-pcre' '--disable-strip' '--enable-redis' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_copy:mod_deflate:mod_ifversion:mod_geoip:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession:mod_auth_otp:mod_tls_redis:mod_wrap2_redis:mod_redis:mod_memcache:mod_tls_memcache:mod_readme:mod_snmp' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fdebug-prefix-map=/build/proftpd-dfsg-oI4YZ3/proftpd-dfsg-1.3.6c=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lcap  -lpam -lsupp -lattr -lnsl -lresolv -lresolv -lcrypt -ldl -lhiredis -lmemcachedutil -lmemcached  -pthread

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /run/proftpd.pid
    Scoreboard File:
      /run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + Redis support
    - Sodium support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

when i try to transfer file via filezila, where with SSL/TLS Explicit Encryption, filezila log as:
```
Status:	Starting upload of D:\subbiah\FTPS_Files\HBK\test\00780333_24I10428I_10427.HBK
Status:	Retrieving directory listing of "/"...
Status:	Logged in
Status:	Starting upload of D:\subbiah\FTPS_Files\HBK\test\00780333_24I10427I_10426.HBK
Status:	Retrieving directory listing of "/"...
Command:	TYPE I
Response:	200 Type set to I
Command:	PASV
Response:	227 Entering Passive Mode (18,118,63,28,192,7).
Command:	MLSD
Error:	GnuTLS error -110: The TLS connection was non-properly terminated.
Status:	Server did not properly shut down TLS connection
Error:	The data connection could not be established: ECONNABORTED - Connection aborted
Response:	150 Opening BINARY mode data connection for MLSD
Response:	425 Unable to build data connection: Operation not permitted
Command:	SIZE 00780333_24I10428I_10427.HBK
Response:	550 MLSD: Operation not permitted
Command:	PASV
Response:	550 00780333_24I10428I_10427.HBK: No such file or directory
Command:	PORT 192,168,166,190,226,72
Response:	227 Entering Passive Mode (18,118,63,28,192,7).
Command:	STOR 00780333_24I10428I_10427.HBK
Response:	500 Illegal PORT command
Error:	Critical file transfer error
Status:	Starting upload of D:\subbiah\FTPS_Files\HBK\test\00780333_24I10426I_10425.HBK
Status:	Retrieving directory listing of "/"...
Command:	TYPE I
Response:	200 Type set to I
Command:	PASV
Response:	227 Entering Passive Mode (18,118,63,28,192,8).
Command:	MLSD
Error:	GnuTLS error -110: The TLS connection was non-properly terminated.
Status:	Server did not properly shut down TLS connection
Error:	The data connection could not be established: ECONNABORTED - Connection aborted
Response:	150 Opening BINARY mode data connection for MLSD
Response:	425 Unable to build data connection: Operation not permitted
Command:	SIZE 00780333_24I10427I_10426.HBK
Response:	550 MLSD: Operation not permitted
Command:	PASV
Response:	550 00780333_24I10427I_10426.HBK: No such file or directory
Command:	PORT 192,168,166,190,226,80
Response:	227 Entering Passive Mode (18,118,63,28,192,2).
Command:	STOR 00780333_24I10427I_10426.HBK
Response:	500 Illegal PORT command
Error:	Critical file transfer error
```

proftpd server log as:
```
2024-08-25 12:36:53,823 mod_tls/2.7[865]: TLS/TLS-C requested, starting TLS handshake
2024-08-25 12:36:54,204 mod_tls/2.7[866]: TLS/TLS-C requested, starting TLS handshake
2024-08-25 12:36:54,643 mod_tls/2.7[865]: TLSv1.3 connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
2024-08-25 12:36:55,144 mod_tls/2.7[866]: TLSv1.3 connection accepted, using cipher TLS_AES_256_GCM_SHA384 (256 bits)
2024-08-25 12:36:56,503 mod_tls/2.7[865]: Protection set to Private
2024-08-25 12:36:56,884 mod_tls/2.7[866]: Protection set to Private
2024-08-25 12:37:01,385 mod_tls/2.7[865]: starting TLS negotiation on data connection
2024-08-25 12:37:01,385 mod_tls/2.7[865]: unable to accept TLS connection: system call error: [0] Success
2024-08-25 12:37:01,385 mod_tls/2.7[865]: unable to open data connection: TLS negotiation failed
```

help me to resolve the error.
